// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhAbbyOUj0CzJVUJWNw_bDImGZ0vnI_m4',
    appId: '1:544635807392:web:2d843a564e69df38540bc5',
    messagingSenderId: '544635807392',
    projectId: 'ocp-energy-monitor',
    authDomain: 'ocp-energy-monitor.firebaseapp.com',
    databaseURL: 'https://ocp-energy-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ocp-energy-monitor.firebasestorage.app',
    measurementId: 'G-Y99CH6VK3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBCTL233FZK16wtdoIcJM9OyvV4Qa8Lw',
    appId: '1:544635807392:android:db0d85b9a414dede540bc5',
    messagingSenderId: '544635807392',
    projectId: 'ocp-energy-monitor',
    databaseURL: 'https://ocp-energy-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ocp-energy-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCTcQ0GkFXwK9_Q7uL5bL_hQdAL0XV5A',
    appId: '1:544635807392:ios:5cccfee96c6f27ea540bc5',
    messagingSenderId: '544635807392',
    projectId: 'ocp-energy-monitor',
    databaseURL: 'https://ocp-energy-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ocp-energy-monitor.firebasestorage.app',
    iosBundleId: 'com.example.kofertDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCTcQ0GkFXwK9_Q7uL5bL_hQdAL0XV5A',
    appId: '1:544635807392:ios:5cccfee96c6f27ea540bc5',
    messagingSenderId: '544635807392',
    projectId: 'ocp-energy-monitor',
    databaseURL: 'https://ocp-energy-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ocp-energy-monitor.firebasestorage.app',
    iosBundleId: 'com.example.kofertDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhAbbyOUj0CzJVUJWNw_bDImGZ0vnI_m4',
    appId: '1:544635807392:web:2d843a564e69df38540bc5',
    messagingSenderId: '544635807392',
    projectId: 'ocp-energy-monitor',
    authDomain: 'ocp-energy-monitor.firebaseapp.com',
    databaseURL: 'https://ocp-energy-monitor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ocp-energy-monitor.firebasestorage.app',
    measurementId: 'G-Y99CH6VK3Y',
  );
}